
exports.RENTHERO_COMM_LOGS = 'RENTHERO_COMM_LOGS'
exports.RENTHERO_QALTA_SETS = 'RENTHERO_QALTA_SETS'
exports.RENTHERO_INTENTS_HIT = 'RENTHERO_INTENTS_HIT'
exports.RENTHERO_USER_REACTIONS = 'RENTHERO_USER_REACTIONS'
